GAdemo/Models/EcommerceViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using GAdemo.Models.GAdata;

namespace GAdemo.Models
{
    public class EcommerceViewModel
    {
        public GAbasket Basket { get; set; }
        public GAproduct Product { get; set; }
        public List<GAproduct> Products { get; set; }
        public GApurchase Purchase { get; set; }
        public string Message { get; set; }

        public GAproduct AddedGAproduct { get; set; }
    }
}

GAdemo/Controllers/EcommerceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Caching;
using System.Web.Mvc;
using GAdemo.Models;
using GAdemo.Models.GAdata;

namespace GAdemo.Controllers
{
    public class EcommerceController : Controller
    {
        public ActionResult Ecommerce()
        {
            var model = new EcommerceViewModel {Products = GetProducts()};
            return View(model);
        }

        [HttpPost]
        public ActionResult AddToBasket(FormCollection formCollection)
        {
            var productId = formCollection.Get("ProductId");
            var cachedBasket = BasketController.GetBasket();
            var basket = cachedBasket ?? new GAbasket() { BasketId = Utils.Utils.RandomString(16), Items = new List<GAproduct>() };
            var addedProduct = Mockdata.Mockdata.GetMockProduct(Convert.ToInt32(productId));
            basket.Items.Add(addedProduct);
            var cachedCart = System.Web.HttpContext.Current.Cache.Add("GAbasket", basket, null, DateTime.Now.AddMinutes(30), Cache.NoSlidingExpiration, CacheItemPriority.High, null);

            var model = new EcommerceViewModel
            {
                Basket = basket,
                AddedGAproduct = addedProduct,
                Product = addedProduct,
                Message = addedProduct.Name+" lagt til i handlekurv."
            };
            return View("~/Views/Ecommerce/Product.cshtml", model);
        }

        public ActionResult AddToBasket()
        {
            var cachedBasket = BasketController.GetBasket();
            
            var model = new EcommerceViewModel
            {
                Basket = cachedBasket
            };
            return View("~/Views/Ecommerce/Product.cshtml", model);
        }


        [HttpPost]
        public ActionResult GoToProduct(FormCollection formCollection)
            {
            var productId = formCollection.Get("Products");
            
            var product = Mockdata.Mockdata.GetMockProduct(Convert.ToInt32(productId));
            
            var model = new EcommerceViewModel { Product = product};
            return View("~/Views/Ecommerce/Product.cshtml", model);
        }

        public ActionResult GoToProduct()
        {
            var model = new EcommerceViewModel { };
            return View("~/Views/Ecommerce/Product.cshtml", model);
        }

        public ActionResult Product()
        {
            var model = new EcommerceViewModel { Basket = BasketController.GetBasket() };
            return View(model);
        }

        public ActionResult Checkout()
        {
            var model = new EcommerceViewModel {Basket = BasketController.GetBasket()};
            return View(model);
        }
        public ActionResult Orderconfirmation()
        {
            var model = new EcommerceViewModel {Basket = BasketController.GetBasket()};
            model.Purchase = Mockdata.Mockdata.GetGApurchase(model.Basket);
            System.Web.HttpContext.Current.Cache.Remove("GAbasket");
            return View(model);
        }

        private GAproduct GetProduct(int productNumber)
        {
            return Mockdata.Mockdata.GetMockProduct(productNumber);
        }

        private List<GAproduct> GetProducts()
        {
            return Mockdata.Mockdata.GetGAproducts();
        }
    }
}

GAdemo/Views/Ecommerce/Checkout.cshtml
@{
    ViewBag.Title = "Checkout";

    Layout = "~/Views/Shared/_Layout.cshtml";
    var itemsInBasket = Model.Basket?.Items?.Count ?? 0;


}
@model GAdemo.Models.EcommerceViewModel

<div>
    <h1>Simple checkout pages</h1>

    <p>Products in cart: @itemsInBasket</p>

    @if (Model.Basket != null && Model.Basket.Items != null)
    {
        foreach (var product in Model.Basket.Items)
        {
            <span>@product.Name</span>
            <br/>
        }
    }



    @Html.ActionLink("Orderconfirmation", "Orderconfirmation", "Ecommerce")
</div>
@if (Model.Basket?.Items != null)
{
    <script>
/**
 * A function to handle a click on a checkout button. This function uses the eventCallback
 * data layer variable to handle navigation after the ecommerce data has been sent to Google Analytics.
 */

function onCheckout() {
    dataLayer.push({
        'event': 'checkout',
        'ecommerce': {
            'checkout': {
                'actionField': { 'step': 1, 'option': 'Visa' },
                'products': [
                    @foreach (var produt in Model.Basket.Items)
                    {
                        <text>{
                        'name': '@produt.Name',
                        'id': '@produt.Id',
                        'price': '@produt.Price',
                        'brand': '@produt.Brand',
                        'category': '@produt.Category',
                        'variant': '@produt.Variant',
                        'quantity': @produt.Quantity
                    }, </text>
                    }
                        ]
                    }
                }
            });
}

onCheckout();
    </script>
}

GAdemo/Views/Ecommerce/Ecommerce.cshtml
@{
    ViewBag.Title = "Ecommerce intro";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model GAdemo.Models.EcommerceViewModel
<div>
    <h1>Ecommerce start here</h1>

    <h3>Chose on of the available products</h3>



    @using (Html.BeginForm("GoToProduct", "Ecommerce", FormMethod.Post))
    {
        @Html.LabelFor(m => m.Products)
        @Html.DropDownListFor(m => m.Products, Model.Products.Select(p => new SelectListItem
        {
            Value = p.Id,
            Text = p.Name,
            Selected = p.Id == "10"
        }))

        <input class="button" id="submit" type="submit" value="See product"/>
    }

    <p>
        <h3>Here are some useful links</h3>
        <ul>
            <li><a href="https://developers.google.com/tag-manager/enhanced-ecommerce" target="_blank">https://developers.google.com/tag-manager/enhanced-ecommerce</a></li>
            <li><a href="http://www.simoahava.com/analytics/enhanced-ecommerce-tips-and-learnings/" target="_blank">http://www.simoahava.com/analytics/enhanced-ecommerce-tips-and-learnings/</a></li>
        </ul>
    </p>
</div>
<script>
    // Measures product impressions and also tracks a standard
    // pageview for the tag configuration.
    // Product impressions are sent by pushing an impressions object
    // containing one or more impressionFieldObjects.
    dataLayer.push({
        'ecommerce': {
            'currencyCode': 'NOK',                       // Local currency is optional.
            'impressions': [
                @foreach (var product in Model.Products)
        {
            <text>{
                    'name':'@product.Name', // Name or ID is required.
                    'id': '@product.Id',
                    'price': '@product.Price',
                    'brand': '@product.Brand',
                    'category': '@product.Category',
                    'variant': '@product.Variant',
                    'list': '@product.List',
                    'position': @product.Position
                    },</text>
        }
            ]
        }
    });
</script>

GAdemo/Views/Ecommerce/Orderconfirmation.cshtml
@{
    ViewBag.Title = "Orderconfirmation";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var itemsInBasket = Model.Basket?.Items?.Count ?? 0;
}
@model GAdemo.Models.EcommerceViewModel
<div>
    <h1>En enkel ordre konfirmation</h1>

    <p>Products in orde: @itemsInBasket</p>

    @if (Model.Basket?.Items != null)
    {
        foreach (var product in Model.Basket.Items)
        {
            <span>@product.Name</span>
            <br />
        }
    } else{
        <h3>No product purchased</h3>
    }
</div>
@if (Model.Basket?.Items != null)
{
    <script>
        // Send transaction data with a pageview if available
        // when the page loads. Otherwise, use an event when the transaction
        // data becomes available.
        dataLayer.push({
            'ecommerce': {
                'purchase': {
                    'actionField': {
                        'id': '@Model.Purchase.Id',                         // Transaction ID. Required for purchases and refunds.
                        'affiliation': '@Model.Purchase.Affiliation',
                        'revenue': '@Model.Purchase.Revenue',                     // Total transaction value (incl. tax and shipping)
                        'tax': '@Model.Purchase.Tax',
                        'shipping': '@Model.Purchase.Shipping',
                        'coupon': '@Model.Purchase.Cupon'
                    },
                    'products': [
                         @foreach (var produt in Model.Basket.Items)
             {
                 <text>{
                             'name': '@produt.Name',
                             'id': '@produt.Id',
                             'price': '@produt.Price',
                             'brand': '@produt.Brand',
                             'category': '@produt.Category',
                             'variant': '@produt.Variant',
                             'quantity': @produt.Quantity,
                             'cupon': '@produt.Cupon'
                         },  </text>
             }
                    ]
                }
            }
        });
    </script>
}

GAdemo/Views/Ecommerce/Product.cshtml
@{
    ViewBag.Title = "Product page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model GAdemo.Models.EcommerceViewModel
<div>
    @if(Model.Product != null) { 

    <h1>@Model.Product.Name</h1>

        <p>
            <strong>Brand: </strong>@Model.Product.Brand<br/>
            <strong>Brand: </strong>@Model.Product.Variant<br />
            <strong>Price: </strong>@Model.Product.Price<br/>
            <strong>Category: </strong>@Model.Product.Category<br />
        </p>



    using (Html.BeginForm("AddToBasket", "Ecommerce", FormMethod.Post))
    {
        @Html.Hidden("ProductId", Model.Product.Id)

        <input class="button" id="submit" type="submit" value="Add @Model.Product.Name to basket"/>
    }

    <p><strong>@Model.Message</strong></p>
        <p>
            Go to chekcout here: @Html.ActionLink("Checkout", "Checkout", "Ecommerce")
        </p>
        <p>Or add anoterproduct here: @Html.ActionLink("Product overview", "Ecommerce", "Ecommerce")</p>
    }
    else
    {
        <h2>No product choosen. Go back to product overview here: @Html.ActionLink("Product overview", "Ecommerce", "Ecommerce")</h2>
    }
</div>
<script>
    // Measures product impressions and also tracks a standard
    // pageview for the tag configuration.
    // Product impressions are sent by pushing an impressions object
    // containing one or more impressionFieldObjects.
    @if (Model.Product != null) {
    <text>
    dataLayer.push({
        'ecommerce': {
            'currencyCode': 'NOK', // Local currency is optional.
            'detail': {
                'products': [
                    {
                        'name': '@Model.Product.Name', // Name or ID is required.
                        'id': '@Model.Product.Id',
                        'price': '@Model.Product.Price',
                        'brand': '@Model.Product.Brand',
                        'category': '@Model.Product.Category',
                        'variant': '@Model.Product.Variant',
                        'list': '@Model.Product.List',
                        'position': @Model.Product.Position
                        }
                ]
            }
        }
    });
    </text>
    }

    @if (Model.AddedGAproduct != null){
    <text>
    // Measure adding a product to a shopping cart by using an 'add' actionFieldObject
    // and a list of productFieldObjects.
    dataLayer.push({
        'event': 'addToCart',
        'ecommerce': {
            'currencyCode': 'EUR',
            'add': {                                // 'add' actionFieldObject measures.
                'products': [{                        //  adding a product to a shopping cart.
                    'name': '@Model.AddedGAproduct.Name',
                    'id': '@Model.AddedGAproduct.Id',
                    'price': '@Model.AddedGAproduct.Price',
                    'brand': '@Model.AddedGAproduct.Brand',
                    'category': '@Model.AddedGAproduct.Category',
                    'variant': '@Model.AddedGAproduct.Variant',
                    'quantity': @Model.AddedGAproduct.Quantity
                    }]
            }
        }
    });</text>
    }
</script>